[pytest]
testpaths = tests
filterwarnings =
    default
    error::DeprecationWarning:slack_main
    error::DeprecationWarning:gong_main
    error::DeprecationWarning:gong_api
    error::DeprecationWarning:config_main
    error::DeprecationWarning:shared\..*
